version: 2.1
jobs:
  test:
    docker:
      - image: cimg/python:3.10 # Specify your project environment language/version
    steps:
      - checkout # Pulls your code from GitHub
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run Tests
          command: pytest github_api.py

workflows:
  run-tests:
    jobs:
      - test